### ISSUE TITLE
user_input.txt

### ISSUE THREAD

**Issue by VincentGreffe** [Morteza-M-Saber/BacGWASim#1]
Dear Morteza,

BacGWASim seems like a very interesting tool for comparison of GWAS techniques and would love to try it out!
However I currently cannot get it to work. 
I get an error stating it does not find 'Inputs/user_input.txt' and SnakefilePhylogeny. 
Do you have any insight on how to solve this?

Kind regards,

Vincent

**Comment by Morteza-M-Saber** [comment]
Hi Vincent and thanks for interest in using BacGWASim,
This bug is solved in BacGWASim1.2.
